// Constants for Global State Management
export const TOGGLE_LOGIN_BOX = "TOGGLE_LOGIN_BOX";

export const INCREMENT_PAGE_COUNT = "INCREMENT_PAGE_COUNT";
export const DECREMENT_PAGE_COUNT = "DECREMENT_PAGE_COUNT";
export const RESET_PAGE_COUNT = "RESET_PAGE_COUNT";

// Constants for User reducer
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

// User portfolio and website related constants
export const GET_ALL_USER_PORTFOLIO_REQUEST = "GET_ALL_USER_PORTFOLIO_REQUEST";
export const GET_ALL_USER_PORTFOLIO_SUCCESS = "GET_ALL_USER_PORTFOLIO_SUCCESS";
export const GET_ALL_USER_PORTFOLIO_FAILURE = "GET_ALL_USER_PORTFOLIO_FAILURE";

export const CREATE_NEW_PORTFOLIO_REQUEST = "CREATE_NEW_PORTFOLIO_REQUEST";
export const CREATE_NEW_PORTFOLIO_SUCCESS = "CREATE_NEW_PORTFOLIO_SUCCESS";
export const CREATE_NEW_PORTFOLIO_FAILURE = "CREATE_NEW_PORTFOLIO_FAILURE";

export const SET_CURRENT_PORTFOLIO = "SET_CURRENT_PORTFOLIO";
export const CLEAR_CURRENT_PORTFOLIO = "CLEAR_CURRENT_PORTFOLIO";

export const GET_PORTFOLIO_DETAILS_REQUEST = "GET_PORTFOLIO_DETAILS_REQUEST";
export const GET_PORTFOLIO_DETAILS_SUCCESS = "GET_PORTFOLIO_DETAILS_SUCCESS";
export const GET_PORTFOLIO_DETAILS_FAILURE = "GET_PORTFOLIO_DETAILS_FAILURE";

export const RESET_ALL_PORTFOLIO_DETAILS = "RESET_ALL_PORTFOLIO_DETAILS";

// User meta data related constants

export const UPDATE_USER_META_DATA_REQUEST = "UPDATE_USER_META_DATA_REQUEST";
export const UPDATE_USER_META_DATA_SUCCESS = "UPDATE_USER_META_DATA_SUCCESS";
export const UPDATE_USER_META_DATA_FAILURE = "UPDATE_USER_META_DATA_FAILURE";

export const ADD_NEW_EDUCATION = "ADD_NEW_EDUCATION";
export const EDIT_EDUCATION = "EDIT_EDUCATION";
export const ADD_NEW_EXPERIENCE = "ADD_NEW_EXPERIENCE";


export const PORTFOLIO_METADATA_REQUEST = "PORTFOLIO_METADATA_REQUEST";
export const PORTFOLIO_METADATA_SUCCESS = "PORTFOLIO_METADATA_SUCCESS";
export const PORTFOLIO_METADATA_FAILURE = "PORTFOLIO_METADATA_FAILURE";

export const PORTFOLIO_ALL_EDUCATION_REQUEST = "PORTFOLIO_ALL_EDUCATION_REQUEST";
export const PORTFOLIO_ALL_EDUCATION_SUCCESS = "PORTFOLIO_ALL_EDUCATION_SUCCESS";   
export const PORTFOLIO_ALL_EDUCATION_FAILURE = "PORTFOLIO_ALL_EDUCATION_FAILURE";

export const PORTFOLIO_ALL_EXPERIENCE_REQUEST = "PORTFOLIO_ALL_EXPERIENCE_REQUEST";
export const PORTFOLIO_ALL_EXPERIENCE_SUCCESS = "PORTFOLIO_ALL_EXPERIENCE_SUCCESS";
export const PORTFOLIO_ALL_EXPERIENCE_FAILURE = "PORTFOLIO_ALL_EXPERIENCE_FAILURE";

export const PORTFOLIO_SKILLS_REQUEST = "PORTFOLIO_SKILLS_REQUEST";
export const PORTFOLIO_SKILLS_SUCCESS = "PORTFOLIO_SKILLS_SUCCESS";
export const PORTFOLIO_SKILLS_FAILURE = "PORTFOLIO_SKILLS_FAILURE";

export const PORTFOLIO_PROJECTS_REQUEST = "PORTFOLIO_PROJECTS_REQUEST";
export const PORTFOLIO_PROJECTS_SUCCESS = "PORTFOLIO_PROJECTS_SUCCESS";
export const PORTFOLIO_PROJECTS_FAILURE = "PORTFOLIO_PROJECTS_FAILURE";

export const PORTFOLIO_SERVICES_REQUEST = "PORTFOLIO_SERVICES_REQUEST";
export const PORTFOLIO_SERVICES_SUCCESS = "PORTFOLIO_SERVICES_SUCCESS";
export const PORTFOLIO_SERVICES_FAILURE = "PORTFOLIO_SERVICES_FAILURE";

export const PORTFOLIO_TESTIMONIALS_REQUEST = "PORTFOLIO_TESTIMONIALS_REQUEST";
export const PORTFOLIO_TESTIMONIALS_SUCCESS = "PORTFOLIO_TESTIMONIALS_SUCCESS";
export const PORTFOLIO_TESTIMONIALS_FAILURE = "PORTFOLIO_TESTIMONIALS_FAILURE";

export const PORTFOLIO_WEBSITE_DETAILS_REQUEST = "PORTFOLIO_WEBSITE_DETAILS_REQUEST";
export const PORTFOLIO_WEBSITE_DETAILS_SUCCESS = "PORTFOLIO_WEBSITE_DETAILS_SUCCESS";
export const PORTFOLIO_WEBSITE_DETAILS_FAILURE = "PORTFOLIO_WEBSITE_DETAILS_FAILURE";


export const PAGE_LOADING = "PAGE_LOADING";
export const PAGE_LOADED = "PAGE_LOADED";