// Constants for Global State Management
export const TOGGLE_LOGIN_BOX = "TOGGLE_LOGIN_BOX";

// Constants for User reducer
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

// User portfolio and website related constants
export const GET_ALL_USER_PORTFOLIO_REQUEST = "GET_ALL_USER_PORTFOLIO_REQUEST";
export const GET_ALL_USER_PORTFOLIO_SUCCESS = "GET_ALL_USER_PORTFOLIO_SUCCESS";
export const GET_ALL_USER_PORTFOLIO_FAILURE = "GET_ALL_USER_PORTFOLIO_FAILURE";

export const CREATE_NEW_PORTFOLIO_REQUEST = "CREATE_NEW_PORTFOLIO_REQUEST";
export const CREATE_NEW_PORTFOLIO_SUCCESS = "CREATE_NEW_PORTFOLIO_SUCCESS";
export const CREATE_NEW_PORTFOLIO_FAILURE = "CREATE_NEW_PORTFOLIO_FAILURE";

export const SET_CURRENT_PORTFOLIO = "SET_CURRENT_PORTFOLIO";
export const CLEAR_CURRENT_PORTFOLIO = "CLEAR_CURRENT_PORTFOLIO";